Machine Learning 2019 - 2020 <br>
Week 1 - Workshop on Python preliminaries <br>
Lecturer: Dr George Leontidis <br>
Demonstrators: Wayne Andrew, Francesco Del Duchetto, George Onoufriou <br>

# INTRODUCTION <br>

As we discussed during the lecture this week is devoted on introducing the module and you having the chance to (re) visit some basic principles on python. It also provide you with an introduction to Anaconda and the use of notebook for writing code interactively.
There exists a set of simple examples on numpy. Please try to solve as many as you can. 
Solutions will be provided separately.


# EXERCISE

Please try to fill the gaps in the code below

In [6]:
#Import numpy as np and print the version number
#####

#Insert your code here
import numpy as np
print(np.__version__)

#####

1.16.4


In [25]:
#Create a 1D array of numbers from 0 to 8

#####


#Insert your code here
a = np.arange(9)
a

#####

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
 #Create a 5×5 numpy array of all True’s
    
#####


#Insert your code here
np.full((5,5),True)


#####

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [35]:
#Extract all even numbers from arr
#####
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#Insert your code here
arr[ arr%2 == 0]

#####

array([0, 2, 4, 6, 8])

In [38]:
#Replace all even numbers in arr with -3
#####

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
#Insert your code here
arr[ arr%2 == 0] = -3
arr
#####

array([ 1, -3,  3, -3,  5, -3,  7, -3,  9])

In [72]:
#Convert a 1D array to a 2D array with 2 rows
#####


#Insert your code here
arr = np.arange(14).reshape(2,-129681471)
arr


#####

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [79]:
#Stack arrays a and b vertically

#####

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
#Insert your code here
np.vstack([a,b])



#####

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [80]:
#Stack arrays a and b horizontally

#####

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
#Insert your code here
np.hstack([a,b])

#####

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [83]:
#Get the common items between a and b

#####
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

#Insert your code here
np.intersect1d(a,b)

#####

array([2, 4])

In [84]:
#From array a remove all items present in array b

#####

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
#Insert your code here
np.setdiff1d(b,a)
# Desired Output array([1,2,3,4])
#####

array([6, 7, 8, 9])

In [85]:
#Get the positions where elements of a and b match

#####

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
#Insert your code here
np.where(a==b)
# Desired Output (array([1, 3, 5, 7]),)

#####

(array([1, 3, 5, 7], dtype=int64),)

In [100]:
#Convert the function maxx that works on two scalars, to work on two arrays.


#####

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(2, 5)
get_max = np.vectorize(maxx,otypes=[float])
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
get_max(a,b)
# Desired Output 
#a = np.array([5, 7, 9, 8, 6, 4, 5])
#b = np.array([6, 3, 4, 8, 9, 7, 1])
#pair_max(a, b)
# array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

#####



array([6., 7., 9., 8., 9., 7., 5.])

In [102]:
#How to swap two rows in a 2d numpy array?
#Swap rows 1 and 2 in the array arr:

arr = np.arange(9).reshape(3,3)
arr[[1,0,2],:]

#desired output
#> array([[3, 4, 5],
#>        [0, 1, 2],
#>        [6, 7, 8]])

####

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [181]:
#Print or show only 4 decimal places of the numpy array rand_arr

#Input included
rand_arr = np.random.random((5,3))

#Add the part here to create the random array
np.set_printoptions(precision=4)
rand_arr[1:5]

# Limit the output to 4 decimal points


#desired output something of that sort
#> array([[ 0.4783,  0.2209,  0.9993],
#>        [ 0.3868,  0.1347,  0.2191],
#>        [ 0.3491,  0.2374,  0.6212],
#>        [ 0.8909,  0.4318,  0.4703]])

array([[0.9294, 0.9046, 0.4808],
       [0.6989, 0.0576, 0.7118],
       [0.3612, 0.5865, 0.842 ],
       [0.2642, 0.203 , 0.9636]])

In [183]:
#Find the mean, median, standard deviation of iris's sepallength (1st column)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepalwidth = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[1])

# add your code here
mu, med, sd = np.mean(sepalwidth), np.median(sepalwidth), np.std(sepalwidth)
print(mu, med, sd)
#Output of that sort:
#3.054 3.0 0.432146580071

3.0540000000000003 3.0 0.4321465800705435


In [185]:
#Create a normalized form of iris's sepalwidth whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepalwidth = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[1])

# code here
Smax, Smin = sepalwidth.max(), sepalwidth.min()
S = (sepalwidth - Smin)/sepalwidth.ptp()
print(S)
#desired output
#[ 0.625       0.41666667  0.5         0.45833333  0.66666667  0.79166667
# 0.58333333  0.58333333  0.375       0.45833333  0.70833333  0.58333333
#0.41666667  0.41666667  0.83333333  1.          0.79166667  0.625       0.75
# 0.75        0.58333333  0.70833333  0.66666667  0.54166667  0.58333333
# 0.41666667  0.58333333  0.625       0.58333333  0.5         0.45833333
# 0.58333333  0.875       0.91666667  0.45833333  0.5         0.625
#0.45833333  0.41666667  0.58333333  0.625       0.125       0.5         0.625
#0.75        0.41666667  0.75        0.5         0.70833333  0.54166667
#0.5         0.5         0.45833333  0.125       0.33333333  0.33333333
#0.54166667  0.16666667  0.375       0.29166667  0.          0.41666667
#0.08333333  0.375       0.375       0.45833333  0.41666667  0.29166667
#0.08333333  0.20833333  0.5         0.33333333  0.20833333  0.33333333
#0.375       0.41666667  0.33333333  0.41666667  0.375       0.25
#0.16666667  0.16666667  0.29166667  0.29166667  0.41666667  0.58333333
#0.45833333  0.125       0.41666667  0.20833333  0.25        0.41666667
#0.25        0.125       0.29166667  0.41666667  0.375       0.375
#0.20833333  0.33333333  0.54166667  0.29166667  0.41666667  0.375
#0.41666667  0.41666667  0.20833333  0.375       0.20833333  0.66666667
#0.5         0.29166667  0.41666667  0.20833333  0.33333333  0.5
#0.41666667  0.75        0.25        0.08333333  0.5         0.33333333
#0.33333333  0.29166667  0.54166667  0.5         0.33333333  0.41666667
#0.33333333  0.41666667  0.33333333  0.75        0.33333333  0.33333333
#0.25        0.41666667  0.58333333  0.45833333  0.41666667  0.45833333
#0.45833333  0.45833333  0.29166667  0.5         0.54166667  0.41666667
#0.20833333  0.41666667  0.58333333  0.41666667]


[0.625  0.4167 0.5    0.4583 0.6667 0.7917 0.5833 0.5833 0.375  0.4583
 0.7083 0.5833 0.4167 0.4167 0.8333 1.     0.7917 0.625  0.75   0.75
 0.5833 0.7083 0.6667 0.5417 0.5833 0.4167 0.5833 0.625  0.5833 0.5
 0.4583 0.5833 0.875  0.9167 0.4583 0.5    0.625  0.4583 0.4167 0.5833
 0.625  0.125  0.5    0.625  0.75   0.4167 0.75   0.5    0.7083 0.5417
 0.5    0.5    0.4583 0.125  0.3333 0.3333 0.5417 0.1667 0.375  0.2917
 0.     0.4167 0.0833 0.375  0.375  0.4583 0.4167 0.2917 0.0833 0.2083
 0.5    0.3333 0.2083 0.3333 0.375  0.4167 0.3333 0.4167 0.375  0.25
 0.1667 0.1667 0.2917 0.2917 0.4167 0.5833 0.4583 0.125  0.4167 0.2083
 0.25   0.4167 0.25   0.125  0.2917 0.4167 0.375  0.375  0.2083 0.3333
 0.5417 0.2917 0.4167 0.375  0.4167 0.4167 0.2083 0.375  0.2083 0.6667
 0.5    0.2917 0.4167 0.2083 0.3333 0.5    0.4167 0.75   0.25   0.0833
 0.5    0.3333 0.3333 0.2917 0.5417 0.5    0.3333 0.4167 0.3333 0.4167
 0.3333 0.75   0.3333 0.3333 0.25   0.4167 0.5833 0.4583 0.4167 0.4583
 0.4583 0.458